/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.awt.event.*;
   

/**
 *
 * @author Asad Computers
 */

public class ManagerDashboard extends javax.swing.JFrame {
    private services.ProductService productService;   


    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManagerDashboard.class.getName());

    /**
     * Creates new form ManagerDashboard
     */
   



    public ManagerDashboard() {
        initComponents();
        

Timer timer = new Timer(50, new ActionListener() {
   
    int x = 0; 
    public void actionPerformed(ActionEvent e) {
        
        x += 2;

        
        if (x > jPanelText.getWidth()) {
            x = -jLabelText.getWidth();
        }

        
        jLabelText.setLocation(x, jLabelText.getY());
    }
});
timer.start();
   productService = new services.ProductService();
tabbedPaneMain.setSelectedIndex(0);             
loadProductsToTable();
loadSalesAndRelated();
updateKPIs();                                   
}
    
     
private void loadProductsToTable() {
    try {
        javax.swing.table.DefaultTableModel model = productService.getAllProductsTableModel();
        
        tblProducts.setModel(model);
        
        tblSearchResults.setModel(model);
        tblSortResults.setModel(model);
    } catch (Exception e) {
        System.out.println("loadProductsToTable error: " + e.getMessage());
    }
}





private void updateKPIs() {
    try {
        javax.swing.table.DefaultTableModel model = productService.getAllProductsTableModel();
        lblTotalProducts.setText(String.valueOf(model.getRowCount()));

        int lowCount = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            int stock = Integer.parseInt(model.getValueAt(i, 4).toString()); 
            int min = Integer.parseInt(model.getValueAt(i, 5).toString());  
            if (stock <= min) lowCount++;
        }
        lblLowStock.setText(String.valueOf(lowCount));

       
        javax.swing.table.DefaultTableModel sales = productService.getSalesHistoryModel();
        double total = 0;
        for (int i = 0; i < sales.getRowCount(); i++) {
            Object val = sales.getValueAt(i, 2); 
            if (val != null) total += Double.parseDouble(val.toString());
        }
        lblTotalSales.setText(String.format("%.2f", total));
    } catch (Exception e) {
        System.out.println("updateKPIs error: " + e.getMessage());
    }
}
private void loadSalesAndRelated() {
    try {
        tblSalesHistory.setModel(productService.getSalesHistoryModel());
    } catch (Exception e) {
        System.out.println("loadSalesAndRelated error: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelText = new javax.swing.JPanel();
        jLabelText = new javax.swing.JLabel();
        lblUserRole = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        btnViewStock = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        btnSalesHistory = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnSortAZ = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        tabbedPaneMain = new javax.swing.JTabbedPane();
        tabDashboard = new javax.swing.JPanel();
        lblTotalProductsTitle = new javax.swing.JLabel();
        lblTotalProducts = new javax.swing.JLabel();
        lblLowStockTitle = new javax.swing.JLabel();
        lblLowStock = new javax.swing.JLabel();
        lblTotalSalesTitle = new javax.swing.JLabel();
        lblTotalSales = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tabViewStock = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        tabAddProduct = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAddName = new javax.swing.JTextField();
        txtAddCategory = new javax.swing.JTextField();
        txtAddPrice = new javax.swing.JTextField();
        txtAddStock = new javax.swing.JTextField();
        txtAddMin = new javax.swing.JTextField();
        btnSaveProduct = new javax.swing.JButton();
        tabDeleteProduct = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtDeleteId = new javax.swing.JTextField();
        btnDoDelete = new javax.swing.JButton();
        tabSalesHistory = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSalesHistory = new javax.swing.JTable();
        tabSearch = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnDoSearch = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSearchResults = new javax.swing.JTable();
        tabSort = new javax.swing.JPanel();
        btnSortA_Z = new javax.swing.JButton();
        btnSortZA = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblSortResults = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aror Canteen - Manager Dashboard");
        setMaximumSize(new java.awt.Dimension(810, 410));
        setMinimumSize(new java.awt.Dimension(820, 500));
        setPreferredSize(new java.awt.Dimension(820, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelText.setBackground(new java.awt.Color(17, 55, 105));
        jPanelText.setLayout(null);

        jLabelText.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabelText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText.setText("Online Payment System Available !   Just Scan The QR Code");
        jPanelText.add(jLabelText);
        jLabelText.setBounds(10, 40, 430, 21);

        lblUserRole.setForeground(new java.awt.Color(255, 255, 255));
        lblUserRole.setText("Logged in as: Manager");
        jPanelText.add(lblUserRole);
        lblUserRole.setBounds(670, 10, 140, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aror University Canteen ");
        jPanelText.add(jLabel1);
        jLabel1.setBounds(10, 10, 270, 30);

        getContentPane().add(jPanelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 60));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        jPanel3.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnAddProduct.setText("Add product");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btnViewStock.setText("View Stock");
        btnViewStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStockActionPerformed(evt);
            }
        });
        jPanel3.add(btnViewStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        btnDeleteProduct.setText("Delete Product");
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });
        jPanel3.add(btnDeleteProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        btnSalesHistory.setText("Sales History");
        btnSalesHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesHistoryActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalesHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        btnSearch.setText("Search product");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        btnSortAZ.setText("Sort (A to Z)");
        btnSortAZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortAZActionPerformed(evt);
            }
        });
        jPanel3.add(btnSortAZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 140, 400));

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalProductsTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotalProductsTitle.setText("Total Products");
        tabDashboard.add(lblTotalProductsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 31, -1, -1));

        lblTotalProducts.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tabDashboard.add(lblTotalProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 59, 131, 25));

        lblLowStockTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLowStockTitle.setText("Low Stock");
        tabDashboard.add(lblLowStockTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 31, -1, -1));

        lblLowStock.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tabDashboard.add(lblLowStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 59, 96, 25));

        lblTotalSalesTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotalSalesTitle.setText("Total Sales");
        tabDashboard.add(lblTotalSalesTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 31, -1, -1));

        lblTotalSales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tabDashboard.add(lblTotalSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 59, 99, 25));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asad Computers\\Pictures\\Screenshots\\Screenshot 2025-11-15 172945.png")); // NOI18N
        jLabel10.setText("jLabel10");
        tabDashboard.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 179, 250));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel9.setText("SNEAK");
        jLabel9.setAlignmentX(0.5F);
        jLabel9.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel9AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabDashboard.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 70, -1));

        jLabel12.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel12.setText("A");
        tabDashboard.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel13.setText("PEAK!");
        tabDashboard.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 60, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asad Computers\\Pictures\\Screenshots\\Screenshot 2025-11-15 165135.png")); // NOI18N
        tabDashboard.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 250, 140));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asad Computers\\Pictures\\Screenshots\\Screenshot 2025-11-15 183943.png")); // NOI18N
        tabDashboard.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 210, 250));

        tabbedPaneMain.addTab("Dashboard", tabDashboard);

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProducts);

        javax.swing.GroupLayout tabViewStockLayout = new javax.swing.GroupLayout(tabViewStock);
        tabViewStock.setLayout(tabViewStockLayout);
        tabViewStockLayout.setHorizontalGroup(
            tabViewStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabViewStockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))
        );
        tabViewStockLayout.setVerticalGroup(
            tabViewStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );

        tabbedPaneMain.addTab("View Stock", tabViewStock);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Name :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Category : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Price :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Stock : ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Minimum Stock :");

        btnSaveProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSaveProduct.setText("Save");
        btnSaveProduct.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.blue, java.awt.Color.lightGray));
        btnSaveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabAddProductLayout = new javax.swing.GroupLayout(tabAddProduct);
        tabAddProduct.setLayout(tabAddProductLayout);
        tabAddProductLayout.setHorizontalGroup(
            tabAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAddProductLayout.createSequentialGroup()
                .addGroup(tabAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAddProductLayout.createSequentialGroup()
                        .addGroup(tabAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabAddProductLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(tabAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAddProductLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)))
                        .addGroup(tabAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAddStock)
                            .addComponent(txtAddPrice)
                            .addComponent(txtAddCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txtAddName)))
                    .addGroup(tabAddProductLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel2))
                    .addGroup(tabAddProductLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAddMin, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(314, 314, 314))
            .addGroup(tabAddProductLayout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(btnSaveProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabAddProductLayout.setVerticalGroup(
            tabAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAddProductLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(tabAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAddName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAddPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(tabAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAddStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabAddProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAddMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveProduct)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        tabbedPaneMain.addTab("Add Product", tabAddProduct);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Product ID :");

        btnDoDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDoDelete.setText("X Delete X");
        btnDoDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDoDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabDeleteProductLayout = new javax.swing.GroupLayout(tabDeleteProduct);
        tabDeleteProduct.setLayout(tabDeleteProductLayout);
        tabDeleteProductLayout.setHorizontalGroup(
            tabDeleteProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDeleteProductLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(tabDeleteProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDoDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(txtDeleteId))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        tabDeleteProductLayout.setVerticalGroup(
            tabDeleteProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDeleteProductLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(tabDeleteProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDeleteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDoDelete)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        tabbedPaneMain.addTab("Delete Product", tabDeleteProduct);

        tblSalesHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblSalesHistory);

        javax.swing.GroupLayout tabSalesHistoryLayout = new javax.swing.GroupLayout(tabSalesHistory);
        tabSalesHistory.setLayout(tabSalesHistoryLayout);
        tabSalesHistoryLayout.setHorizontalGroup(
            tabSalesHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSalesHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))
        );
        tabSalesHistoryLayout.setVerticalGroup(
            tabSalesHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );

        tabbedPaneMain.addTab("Sales History", tabSalesHistory);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel8.setText("Keyword : ");

        btnDoSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDoSearch.setText("Search ");
        btnDoSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDoSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoSearchActionPerformed(evt);
            }
        });

        tblSearchResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblSearchResults);

        javax.swing.GroupLayout tabSearchLayout = new javax.swing.GroupLayout(tabSearch);
        tabSearch.setLayout(tabSearchLayout);
        tabSearchLayout.setHorizontalGroup(
            tabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSearchLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tabSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))
        );
        tabSearchLayout.setVerticalGroup(
            tabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
        );

        tabbedPaneMain.addTab("Search", tabSearch);

        btnSortA_Z.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSortA_Z.setText("Sort A - Z");
        btnSortA_Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortA_ZActionPerformed(evt);
            }
        });

        btnSortZA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSortZA.setText("Sort Z - A");
        btnSortZA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortZAActionPerformed(evt);
            }
        });

        tblSortResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblSortResults);

        javax.swing.GroupLayout tabSortLayout = new javax.swing.GroupLayout(tabSort);
        tabSort.setLayout(tabSortLayout);
        tabSortLayout.setHorizontalGroup(
            tabSortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSortLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabSortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .addGroup(tabSortLayout.createSequentialGroup()
                        .addComponent(btnSortA_Z)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSortZA)
                        .addContainerGap())))
        );
        tabSortLayout.setVerticalGroup(
            tabSortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabSortLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabSortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSortA_Z)
                    .addComponent(btnSortZA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
        );

        tabbedPaneMain.addTab("Sort", tabSort);

        jDesktopPane1.add(tabbedPaneMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 650, 400));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
   tabbedPaneMain.setSelectedIndex(0);
       updateKPIs();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnViewStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStockActionPerformed
tabbedPaneMain.setSelectedIndex(1);
loadProductsToTable();   
        
    }//GEN-LAST:event_btnViewStockActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
tabbedPaneMain.setSelectedIndex(2);
        
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
tabbedPaneMain.setSelectedIndex(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    private void btnSalesHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesHistoryActionPerformed
tabbedPaneMain.setSelectedIndex(4);
loadSalesAndRelated();
tblSalesHistory.setModel(productService.getSalesHistoryModel()); 
tblSalesHistory.setModel(productService.getSalesHistoryModel());

// TODO add your handling code here:
    }//GEN-LAST:event_btnSalesHistoryActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
tabbedPaneMain.setSelectedIndex(5);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSortAZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortAZActionPerformed
tabbedPaneMain.setSelectedIndex(6);
tblSortResults.setModel(productService.sortProductsByName(true));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSortAZActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
    );

    if (confirm == JOptionPane.YES_OPTION) {
        
        new LoginFrame().setVisible(true);

        
        this.dispose();
    } 
new LoginFrame().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSaveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveProductActionPerformed

        // TODO add your handling code here:
        
        try {
    String name = txtAddName.getText().trim();
    String cat = txtAddCategory.getText().trim();
    double price = Double.parseDouble(txtAddPrice.getText().trim());
    int stock = Integer.parseInt(txtAddStock.getText().trim());
    int min = Integer.parseInt(txtAddMin.getText().trim());
    if (name.isEmpty() || cat.isEmpty()) { JOptionPane.showMessageDialog(this, "Name & Category required"); return; }
    boolean ok = productService.addProduct(name, cat, price, stock, min);
    if (ok) {
        JOptionPane.showMessageDialog(this, "Product added.");
        loadProductsToTable();
        updateKPIs();
        
        txtAddName.setText(""); txtAddCategory.setText(""); txtAddPrice.setText(""); txtAddStock.setText(""); txtAddMin.setText("");
    } else JOptionPane.showMessageDialog(this, "Add failed.");
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Enter valid numbers.");
}

    }//GEN-LAST:event_btnSaveProductActionPerformed
        
    private void btnDoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoDeleteActionPerformed

        // TODO add your handling code here:
    try {
    int id = Integer.parseInt(txtDeleteId.getText().trim());
    int c = JOptionPane.showConfirmDialog(this, "Delete product ID " + id + "?", "Confirm", JOptionPane.YES_NO_OPTION);
    if (c != JOptionPane.YES_OPTION) return;
    boolean ok = productService.deleteProduct(id);
    JOptionPane.showMessageDialog(this, ok ? "Deleted" : "Delete failed");
    loadProductsToTable();
    updateKPIs();
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Enter a valid ID");
}

    }//GEN-LAST:event_btnDoDeleteActionPerformed

    private void btnDoSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoSearchActionPerformed
String key = txtSearch.getText().trim();
if (key.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Enter a search keyword");
    return;
}
tblSearchResults.setModel(productService.searchProductsByName(key));

        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnDoSearchActionPerformed

    private void btnSortA_ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortA_ZActionPerformed
tblSortResults.setModel(productService.sortProductsByName(true));        // TODO add your handling code here:
    }//GEN-LAST:event_btnSortA_ZActionPerformed

    private void btnSortZAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortZAActionPerformed
tblSortResults.setModel(productService.sortProductsByName(false));        // TODO add your handling code here:
    }//GEN-LAST:event_btnSortZAActionPerformed

    private void tblProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductsMouseClicked

if (evt.getClickCount() == 2) {
    int row = tblProducts.getSelectedRow();
    if (row >= 0) {
        txtDeleteId.setText(String.valueOf(tblProducts.getValueAt(row, 0)));
        tabbedPaneMain.setSelectedComponent(tabDeleteProduct);
    }
}
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProductsMouseClicked

    private void jLabel9AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel9AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManagerDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnDoDelete;
    private javax.swing.JButton btnDoSearch;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSalesHistory;
    private javax.swing.JButton btnSaveProduct;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSortAZ;
    private javax.swing.JButton btnSortA_Z;
    private javax.swing.JButton btnSortZA;
    private javax.swing.JButton btnViewStock;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelText;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblLowStock;
    private javax.swing.JLabel lblLowStockTitle;
    private javax.swing.JLabel lblTotalProducts;
    private javax.swing.JLabel lblTotalProductsTitle;
    private javax.swing.JLabel lblTotalSales;
    private javax.swing.JLabel lblTotalSalesTitle;
    private javax.swing.JLabel lblUserRole;
    private javax.swing.JPanel tabAddProduct;
    private javax.swing.JPanel tabDashboard;
    private javax.swing.JPanel tabDeleteProduct;
    private javax.swing.JPanel tabSalesHistory;
    private javax.swing.JPanel tabSearch;
    private javax.swing.JPanel tabSort;
    private javax.swing.JPanel tabViewStock;
    private javax.swing.JTabbedPane tabbedPaneMain;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTable tblSalesHistory;
    private javax.swing.JTable tblSearchResults;
    private javax.swing.JTable tblSortResults;
    private javax.swing.JTextField txtAddCategory;
    private javax.swing.JTextField txtAddMin;
    private javax.swing.JTextField txtAddName;
    private javax.swing.JTextField txtAddPrice;
    private javax.swing.JTextField txtAddStock;
    private javax.swing.JTextField txtDeleteId;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
