/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import services.ProductService;
import java.sql.Connection;




import javax.swing.JTextArea;

/**
 *
 * @author Asad Computers
 */
public class StaffDashboard extends javax.swing.JFrame {
    private services.ProductService productService; 


    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffDashboard.class.getName());

    // To store last sold product info for receipt
private int lastSoldProductId;
private String lastSoldProductName;
private int lastSoldQty;
private double lastSoldTotal;

    
    /**
     * Creates new form StaffDashboard
     */
    public StaffDashboard() {
     
       initComponents();
         productService = new services.ProductService();
    // same as manager dashboard a label at top moving
       Timer timer = new Timer(50, new ActionListener() {
   
    int x = 0; 
    public void actionPerformed(ActionEvent e) {
        
        x += 2;

        
        if (x > jPanelText2.getWidth()) {
            x = -jLabelText2.getWidth();
        }

        
        jLabelText2.setLocation(x, jLabelText2.getY());
    }
});
timer.start();
 updateKPIs();
 loadViewStockTable();      
tblSellProducts.setModel(productService.getAllProductsTableModel());
tblSearchResult.setModel(productService.getAllProductsTableModel());
lblQRCode.setVisible(false);
btnDoSearch.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDoSearchActionPerformed(evt);
    }
});

}
    // update kpis
   
private void updateKPIs() {
        try {
            javax.swing.table.DefaultTableModel model = productService.getAllProductsTableModel();
            lblTotalProducts.setText(String.valueOf(model.getRowCount()));

            int lowCount = 0;
            for (int i = 0; i < model.getRowCount(); i++) {
                int stock = Integer.parseInt(model.getValueAt(i, 4).toString());
                int min = Integer.parseInt(model.getValueAt(i, 5).toString());
                if (stock <= min) lowCount++;
            }
            lblLowStock.setText(String.valueOf(lowCount));

            // Today's sales, for staff maybe use sum of today's transactions
            javax.swing.table.DefaultTableModel sales = productService.getSalesHistoryModel();
            double total = 0;
            for (int i = 0; i < sales.getRowCount(); i++) {
                Object val = sales.getValueAt(i, 2);
                if (val != null) total += Double.parseDouble(val.toString());
            }
            lblTotalSales.setText(String.format("%.2f", total));
        } catch (Exception e) {
            System.out.println("updateKPIs error: " + e.getMessage());
        }
    }

    private void loadViewStockTable() {
        tblViewStock.setModel(productService.getAllProductsTableModel());
    }








    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelText2 = new javax.swing.JPanel();
        jLabelText2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnViewStock = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        tabPane = new javax.swing.JTabbedPane();
        panelDashboard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTotalProducts = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLowStock = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTotalSales = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelViewStock = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewStock = new javax.swing.JTable();
        panelSell = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSellProducts = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtSellQty = new javax.swing.JTextField();
        btnSellNow = new javax.swing.JButton();
        btnShowQR = new javax.swing.JButton();
        btnPrintReceipt = new javax.swing.JButton();
        lblQRCode = new javax.swing.JLabel();
        panelSearch = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnDoSearch = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSearchResult = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Staff Dashboard");
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(820, 500));
        setPreferredSize(new java.awt.Dimension(820, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelText2.setBackground(new java.awt.Color(0, 51, 102));
        jPanelText2.setLayout(null);

        jLabelText2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabelText2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText2.setText("Online Payment System Available !   Just Scan The QR Code");
        jPanelText2.add(jLabelText2);
        jLabelText2.setBounds(10, 40, 430, 21);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aror University Canteen");
        jPanelText2.add(jLabel1);
        jLabel1.setBounds(10, 10, 260, 26);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Logged in as : Staff");
        jPanelText2.add(jLabel2);
        jLabel2.setBounds(680, 10, 110, 16);

        getContentPane().add(jPanelText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 805, 60));

        jPanel1.setMinimumSize(new java.awt.Dimension(120, 383));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 383));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnViewStock.setText("View Stock");
        btnViewStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStockActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, -1));

        btnSell.setText("Sell Product");
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });
        jPanel1.add(btnSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 140, 400));

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        panelDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Total Products");
        panelDashboard.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 31, -1, -1));

        lblTotalProducts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        panelDashboard.add(lblTotalProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 59, 131, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Low Stock");
        panelDashboard.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 31, -1, -1));

        lblLowStock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        panelDashboard.add(lblLowStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 59, 96, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Total Sales");
        jLabel5.setMaximumSize(new java.awt.Dimension(99, 22));
        jLabel5.setMinimumSize(new java.awt.Dimension(99, 22));
        jLabel5.setPreferredSize(new java.awt.Dimension(99, 22));
        panelDashboard.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 31, 130, -1));

        lblTotalSales.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        panelDashboard.add(lblTotalSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 59, 99, 25));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asad Computers\\Pictures\\Screenshots\\Screenshot 2025-11-15 183943.png")); // NOI18N
        panelDashboard.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 240, 220));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asad Computers\\Pictures\\Screenshots\\Screenshot 2025-11-16 154244.png")); // NOI18N
        panelDashboard.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, 220));

        tabPane.addTab("Dashboard", panelDashboard);

        tblViewStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblViewStock);

        javax.swing.GroupLayout panelViewStockLayout = new javax.swing.GroupLayout(panelViewStock);
        panelViewStock.setLayout(panelViewStockLayout);
        panelViewStockLayout.setHorizontalGroup(
            panelViewStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewStockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))
        );
        panelViewStockLayout.setVerticalGroup(
            panelViewStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );

        tabPane.addTab("View Stock ", panelViewStock);

        tblSellProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSellProducts);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Enter Quantity: ");

        btnSellNow.setText("Sell Now ");
        btnSellNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellNowActionPerformed(evt);
            }
        });

        btnShowQR.setText("Show Qr code");
        btnShowQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowQRActionPerformed(evt);
            }
        });

        btnPrintReceipt.setText("Print Receipt");
        btnPrintReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReceiptActionPerformed(evt);
            }
        });

        lblQRCode.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asad Computers\\Pictures\\Screenshots\\Screenshot 2025-11-16 153330.png")); // NOI18N

        javax.swing.GroupLayout panelSellLayout = new javax.swing.GroupLayout(panelSell);
        panelSell.setLayout(panelSellLayout);
        panelSellLayout.setHorizontalGroup(
            panelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSellLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))
            .addGroup(panelSellLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnShowQR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSellNow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrintReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSellQty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblQRCode, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        panelSellLayout.setVerticalGroup(
            panelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSellLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSellLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(panelSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSellQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnShowQR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSellNow)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrintReceipt)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSellLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQRCode)
                        .addGap(20, 20, 20))))
        );

        tabPane.addTab("Sell Product ", panelSell);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Search By Name :");

        btnDoSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDoSearch.setText("Search");
        btnDoSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDoSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoSearchActionPerformed(evt);
            }
        });

        tblSearchResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblSearchResult);

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoSearch)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
        );

        tabPane.addTab("Search", panelSearch);

        jDesktopPane1.add(tabPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 61, 650, 400));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
tabPane.setSelectedIndex(0);
            // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnViewStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStockActionPerformed
tabPane.setSelectedIndex(1);
           // TODO add your handling code here:
    }//GEN-LAST:event_btnViewStockActionPerformed

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
 tabPane.setSelectedIndex(2);
          // TODO add your handling code here:
    }//GEN-LAST:event_btnSellActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
tabPane.setSelectedIndex(3);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
    );

    if (confirm == JOptionPane.YES_OPTION) {
        
        new LoginFrame().setVisible(true);

        
        this.dispose();
    }        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnPrintReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReceiptActionPerformed

        if (lastSoldProductId == 0) {
            JOptionPane.showMessageDialog(this, "No sale yet to print receipt.");
            return;
        }

        String receipt = "----- Receipt -----\n";
        receipt += "Product: " + lastSoldProductName + "\n";
        receipt += "Quantity: " + lastSoldQty + "\n";
        receipt += "Total: " + lastSoldTotal + "\n";
        receipt += "------------------";

        JOptionPane.showMessageDialog(this, receipt, "Receipt", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnPrintReceiptActionPerformed

    private void btnShowQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowQRActionPerformed
        int row = tblSellProducts.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Please select a product first.");
        return;
    }

    String productName = tblSellProducts.getValueAt(row, 1).toString();

    
    

    
    lblQRCode.setVisible(true);
    }//GEN-LAST:event_btnShowQRActionPerformed

    private void btnSellNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellNowActionPerformed

        int row = tblSellProducts.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a product to sell.");
            return;
        }

        String qtyText = txtSellQty.getText().trim();
        if (qtyText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter quantity.");
            return;
        }

        int qty;
        try {
            qty = Integer.parseInt(qtyText);
            if (qty <= 0) {
                JOptionPane.showMessageDialog(this, "Invalid Quantity.");
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid quantity.");
            return;
        }

        int productId = Integer.parseInt(tblSellProducts.getValueAt(row, 0).toString());
        String productName = tblSellProducts.getValueAt(row, 1).toString();

        double price = productService.getProductPriceById(productId);

        String result = productService.sellProduct(productId, qty);
        JOptionPane.showMessageDialog(this, result);

        lastSoldProductId = productId;
        lastSoldProductName = productName;
        lastSoldQty = qty;
        lastSoldTotal = qty * price;

        tblSellProducts.setModel(productService.getAllProductsTableModel());
        tblViewStock.setModel(productService.getAllProductsTableModel());
        updateKPIs();
        txtSellQty.setText("");
        lblQRCode.setText("");

    }//GEN-LAST:event_btnSellNowActionPerformed

    private void btnDoSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoSearchActionPerformed
String keyword = txtSearch.getText().trim();

    DefaultTableModel model;
    if (keyword.isEmpty()) {
        
        model = productService.getAllProductsTableModel();
    } else {
      
        model = productService.searchProductsByName(keyword);
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No products found for: " + keyword);
        }
    }

    tblSearchResult.setModel(model);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StaffDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDoSearch;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPrintReceipt;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSell;
    private javax.swing.JButton btnSellNow;
    private javax.swing.JButton btnShowQR;
    private javax.swing.JButton btnViewStock;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelText2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelText2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblLowStock;
    private javax.swing.JLabel lblQRCode;
    private javax.swing.JLabel lblTotalProducts;
    private javax.swing.JLabel lblTotalSales;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JPanel panelSell;
    private javax.swing.JPanel panelViewStock;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tblSearchResult;
    private javax.swing.JTable tblSellProducts;
    private javax.swing.JTable tblViewStock;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSellQty;
    // End of variables declaration//GEN-END:variables
}
